<?php

/**
 * Certificado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Certificado extends BaseCertificado
{
	public function getIdCertificado() {
		return $this->idCertificado;
	}
	public function setIdCertificado($idCertificado) {
		$this->idCertificado = $idCertificado;
		return $this;
	}
	public function getIdEntidade() {
		return $this->idEntidade;
	}
	public function setIdEntidade($idEntidade) {
		$this->idEntidade = $idEntidade;
		return $this;
	}
	public function getCodigo() {
		return $this->codigo;
	}
	public function setCodigo($codigo) {
		$this->codigo = $codigo;
		return $this;
	}
	public function getDataEmissao() {
		return $this->dataEmissao;
	}
	public function setDataEmissao($dataEmissao) {
		$this->dataEmissao = $dataEmissao;
		return $this;
	}
	public function getEntidade() {
		return $this->Entidade;
	}
	public function setEntidade($Entidade) {
		$this->Entidade = $Entidade;
		return $this;
	}
}