<?php

/**
 * Entidade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Entidade extends BaseEntidade
{
	public function getIdEntidade() {
		return $this->idEntidade;
	}
	public function setIdEntidade($idEntidade) {
		$this->idEntidade = $idEntidade;
		return $this;
	}
	public function getNomeEntidade() {
		return $this->nomeEntidade;
	}
	public function setNomeEntidade($nomeEntidade) {
		$this->nomeEntidade = $nomeEntidade;
		return $this;
	}
	public function getCnpjCpf() {
		return $this->cnpj_cpf;
	}
	public function setCnpjCpf($cnpj_cpf) {
		$this->cnpj_cpf = $cnpj_cpf;
		return $this;
	}
	public function getTelefone() {
		return $this->telefone;
	}
	public function setTelefone($telefone) {
		$this->telefone = $telefone;
		return $this;
	}
	public function getEmail() {
		return $this->email;
	}
	public function setEmail($email) {
		$this->email = $email;
		return $this;
	}
	public function getTipo() {
		return $this->tipo;
	}
	public function setTipo($tipo) {
		$this->tipo = $tipo;
		return $this;
	}
	public function getCertificado() {
		return $this->Certificado;
	}
	public function setCertificado($Certificado) {
		$this->Certificado = $Certificado;
		return $this;
	}
	public function getMatricula() {
		return $this->Matricula;
	}
	public function setMatricula($Matricula) {
		$this->Matricula = $Matricula;
		return $this;
	}
	
	public function inserirEntidade(){
		try{
			$this->save();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarPJ(){
		try{
			return $this->getTable()->findBy('tipo', 'PJ');
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarPF(){
		try{
			return $this->getTable()->findBy('tipo', 'PF');
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarEntidades(){
		try{
			return $this->getTable()->findAll();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarEntidadePorId(){
		try{
			return $this->getTable()->findOneBy('idEntidade', $this->getIdEntidade());
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarEntidadePorCnpjCpf(){
		try{
			return $this->getTable()->findOneBy('cnpj_cpf', $this->getCnpjCpf());
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}