<?php

/**
 * Evento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Evento extends BaseEvento
{
	public function getIdEvento() {
		return $this->idEvento;
	}
	public function setIdEvento($idEvento) {
		$this->idEvento = $idEvento;
		return $this;
	}
	public function getNomeEvento() {
		return $this->nomeEvento;
	}
	public function setNomeEvento($nomeEvento) {
		$this->nomeEvento = $nomeEvento;
		return $this;
	}
	public function getDataInicio() {
		return $this->dataInicio;
	}
	public function setDataInicio($dataInicio) {
		$this->dataInicio = $dataInicio;
		return $this;
	}
	public function getDateFim() {
		return $this->dateFim;
	}
	public function setDateFim($dateFim) {
		$this->dateFim = $dateFim;
		return $this;
	}
	public function getModalidade() {
		return $this->modalidade;
	}
	public function setModalidade($modalidade) {
		$this->modalidade = $modalidade;
		return $this;
	}
	public function getValor() {
		return $this->valor;
	}
	public function setValor($valor) {
		$this->valor = $valor;
		return $this;
	}
	public function getCargaHoraria() {
		return $this->cargaHoraria;
	}
	public function setCargaHoraria($cargaHoraria) {
		$this->cargaHoraria = $cargaHoraria;
		return $this;
	}
	public function getCurso() {
		return $this->Curso;
	}
	public function setCurso($Curso) {
		$this->Curso = $Curso;
		return $this;
	}
}