<?php

/**
 * Membros
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Membros extends BaseMembros
{
	public function getCodMembro() {
		return $this->codMembro;
	}
	public function setCodMembro($codMembro) {
		$this->codMembro = $codMembro;
		return $this;
	}
	public function getNomeMembro() {
		return $this->nomeMembro;
	}
	public function setNomeMembro($nomeMembro) {
		$this->nomeMembro = $nomeMembro;
		return $this;
	}
	public function getAtivo() {
		return $this->ativo;
	}
	public function setAtivo($ativo) {
		$this->ativo = $ativo;
		return $this;
	}
	public function getVinculo() {
		return $this->Vinculo;
	}
	public function setVinculo($Vinculo) {
		$this->Vinculo = $Vinculo;
		return $this;
	}
	
	public function inserirMembros(){
		try{
			$this->save();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarMembrosAtivos(){
		try{
			return $this->getTable()->findBy('ativo', 'S');
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function demitirMembro(){
		try{
			$m = $this->getTable()->findOneBy('codMembro', $this->getCodMembro());
			if($m){
				$m->setAtivo('N');
				$m->save();
			}
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarMembrosInativos(){
		try{
			return $this->getTable()->findBy('ativo', 'N');
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarMembroPorId(){
		try{
			return $this->getTable()->findOneBy('codMembro', $this->getCodMembro());
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function getAdmissao(){
		try{
			$q = Doctrine_Core::getTable('Vinculo')->createQuery()
												->select('dataAdmissao')
												->where('codMembro = '.$this->getCodMembro())
												->orderBy('dataAdmissao asc')
												->limit('1')
												->execute();
			return $q[0]->getDataAdmissao();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function getDemissao(){
		try{
			$q = Doctrine_Core::getTable('Vinculo')->createQuery()
												->select('dataDemissao')
												->where('codMembro = '.$this->getCodMembro())
												->orderBy('dataDemissao desc')
												->limit('1')
												->execute();
			return $q[0]->getDataDemissao();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}